<a href="https://colab.research.google.com/github/muscak/Basics/blob/main/2-%20NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
All list operations are applicable. https://numpy.org/doc/stable/user/absolute_beginners.html 






In [ ]:
# This is based on the Data Analysis with Python - Full Course for Beginners from freeCodeCamp.org

In [ ]:
import numpy as np

In [ ]:
# Allows you to create type specific variables
x = np.int8(4)
x

4

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
a[::2]

array([1, 3, 5])

##Array Types

In [ ]:
# Get the data type of the numpy
a.dtype

dtype('int64')

In [ ]:
c = np.array([1, 2, 3, 4], dtype = np.float)
c

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [ ]:
c.dtype

dtype('float64')

##Dimensions and Shapes

In [ ]:
a = np.array([
    [
      [1, 2, 3],
      [4, 5, 6]
    ],
    [
      [8, 9, 10],
      [10, 11, 12]
    ]
  ]
)

In [ ]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [10, 11, 12]]])

In [ ]:
# Shape of the numpy array
a.shape

(2, 2, 3)

In [ ]:
# Number of dimensions of the numpy array
a.ndim

3

In [ ]:
# Total size (total number of elements) of the numpy array
a.size

12

In [ ]:
a = np.array([
#              0. 1. 2
              [1, 2, 3], #0 
              [4, 5, 6], #1
              [7, 8, 9]  #2
              ]) 
# Returns the array 2nd array in the 2 dimensional numpy array
a[1]

array([4, 5, 6])

In [ ]:
# Returns the 2nd row and 1st column in the 2 dimensional numpy array same a[1, 0]
a[1][0]

4

In [ ]:
# Returns the rows from 1st up to 3rd row of the 2 dimensional numpy array
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Returns all rows, and from 1st column up to 3rd column of the 2 dimensional numpy array
a[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
# Replace all elements of a row with another array
a[1] = np.array([10, 10, 10])
a

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
# Replace all elements of a row with a number
a[2] = 99
a

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Summary Statistics

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Sum of all elements of the array
a.sum()

45

In [ ]:
# Mean of all elements of the array
a.mean() 

5.0

In [ ]:
# Standard deviation of all elements of the array
a.std()

2.581988897471611

In [ ]:
# Variance of all elements of the array
a.var()

6.666666666666667

In [ ]:
# Sum of the elements in the columns
a.sum(axis=0)

array([12, 15, 18])

In [ ]:
# Sum of the elements in the rows
a.sum(axis=1)

array([ 6, 15, 24])

## Vectorized Operations

In [ ]:
# Create NumPy array from 0 untill 4 
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
# This operation does NOT update the numpy array in the memory. NumPy is an immutable first library.
a + 10

array([20, 21, 22, 23])

In [ ]:
# Above opeation didn't impact the numpy array a
a

array([0, 1, 2, 3])

In [ ]:
# This operation updates the numpy array in the memory. "=" operation overrides the immutable behaviour of NumPy.
a += 10

In [ ]:
# Above opeation has impacted the numpy array a
a

array([10, 11, 12, 13])

In [ ]:
b = np.array([10, 10, 10, 10])
b

array([10, 10, 10, 10])

In [ ]:
# Sum of 2 arrays
a + b

array([20, 21, 22, 23])

In [ ]:
# Multiplication of 2 arrays
a * b

array([100, 110, 120, 130])

##Masks

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
# Returns all the elements that are higher than 3
a[a >= 3]

array([3, 4])

In [ ]:
# Returns a boolean array that the elements of array which are higher than or equals to 2 are True
a >= 2

array([False, False,  True,  True,  True])

In [ ]:
a.mean()

2.0

In [ ]:
# Returns all the elements that are higher than the mean of the array
a[a >= a.mean()]

array([2, 3, 4])

In [ ]:
# Returns all elements that are smaller than mean of the array
a[~(a > a.mean())]

array([0, 1, 2])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
# Generates 2 dimentional NumPy array with random integers
a = np.random.randint(100, size=(3,3))
a 

array([[71, 51, 65],
       [64, 31, 62],
       [15, 87, 77]])

In [ ]:
a > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [ ]:
a[a>30]

array([71, 51, 65, 64, 31, 62, 87, 77])

##Linear Algebra

In [ ]:
a = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

In [ ]:
b = np.array([
             [6, 5],
             [4, 3],
             [2, 1]
])

In [ ]:
# Returns the dot product of 2 matrixes
a.dot(b)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
# Returns the cross product of 2 matrixes
a @ b

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
# Transposing a matrix
b.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
b.T @ a

array([[36, 48, 60],
       [24, 33, 42]])

##Size of objects in memory

In [ ]:
import sys

In [ ]:
# Returns the size in bytes
sys.getsizeof(1)

28

In [ ]:
sys.getsizeof(10**100)

72

In [ ]:
# NumPy size is smaller
np.dtype(int).itemsize

8

### Performance

In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(100000)

In [ ]:
%time sum([x**2 for x in l])

CPU times: user 34.3 ms, sys: 1.59 ms, total: 35.9 ms
Wall time: 37.3 ms


333328333350000

In [ ]:
%time np.sum(a**2)

CPU times: user 549 µs, sys: 0 ns, total: 549 µs
Wall time: 560 µs


333328333350000

In [ ]:
# Creates list from 0 to 10 in 5 equal steps
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])